# Implementing a 2 and 3 layer Neural Network

The code in this chapter is based on the article from http://iamtrask.github.io.

And now we are going to implement basic 2 and 3 layers Neural Network.

In [1]:
#the codes
import numpy as np

X = np.array([ [0,0,1],[0,1,1],[1,0,1],[1,1,1] ])
y = np.array([[0,1,1,0]]).T
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1
print syn0
print syn1
for j in xrange(60000):
    l1 = 1/(1+np.exp(-(np.dot(X,syn0))))
    l2 = 1/(1+np.exp(-(np.dot(l1,syn1))))
    l2_delta = (y - l2)*(l2*(1-l2))
    l1_delta = l2_delta.dot(syn1.T) * (l1 * (1-l1))
    syn1 += l1.T.dot(l2_delta)
    syn0 += X.T.dot(l1_delta)
print l2

[[-0.15026312 -0.44991405 -0.21557312  0.78647676]
 [ 0.84262809 -0.87363201  0.71188035  0.96945682]
 [ 0.51045123 -0.79141457 -0.39499845  0.97380321]]
[[-0.62254799]
 [ 0.47081834]
 [-0.10796858]
 [ 0.17203924]]
[[0.00382465]
 [0.99492827]
 [0.99763832]
 [0.00440523]]
