# Implementing a 2 and 3 layer Neural Network

The code in this chapter is based on the article from http://iamtrask.github.io.

And now we are going to implement basic 2 and 3 layers Neural Network.

In [ ]:
#the codes
import numpy as np

X = np.array([ [0,0,1],[0,1,1],[1,0,1],[1,1,1] ])
y = np.array([[0,1,1,0]]).T
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1
print syn0
print syn1
for j in xrange(60000):
    l1 = 1/(1+np.exp(-(np.dot(X,syn0))))
    l2 = 1/(1+np.exp(-(np.dot(l1,syn1))))
    l2_delta = (y - l2)*(l2*(1-l2))
    l1_delta = l2_delta.dot(syn1.T) * (l1 * (1-l1))
    syn1 += l1.T.dot(l2_delta)
    syn0 += X.T.dot(l1_delta)
print l2

[[-0.4841604   0.1659111   0.2957235   0.75947594]
 [-0.10429508  0.88684823 -0.58646235 -0.37150025]
 [-0.50534368 -0.15510722 -0.97379495 -0.63791436]]
[[-0.92755439]
 [ 0.6146175 ]
 [-0.69133293]
 [ 0.29156788]]
[[  7.93299737e-01   7.01151567e-01   5.24117282e-01   8.77515568e-02]
 [  9.61428577e-03   9.86100454e-01   3.78143929e-02   5.20870026e-05]
 [  1.82649453e-02   9.72997835e-01   9.99459120e-01   9.59938687e-01]
 [  4.70565429e-05   9.99083086e-01   9.85060733e-01   1.28094242e-02]]
