<table class="tg">
  <tbody><tr>
    <th class="tg-5rcs" colspan="3">Inputs (l0)</th>
    <th class="tg-5rcs" colspan="4">Hidden Weights (l1)</th>
    <th class="tg-5rcs">Output (l2)</th>
  </tr>
  <tr>
    <td class="tg-4kyz">0</td>
    <td class="tg-4kyz">0</td>
    <td class="tg-4kyz">1</td>
    <td class="tg-4kyz">0.1</td>
    <td class="tg-4kyz">0.2</td>
    <td class="tg-4kyz">0.5</td>
    <td class="tg-4kyz">0.2</td>
    <td class="tg-4kyz">0</td>
  </tr>
  <tr>
    <td class="tg-4kyz">0</td>
    <td class="tg-4kyz">1</td>
    <td class="tg-4kyz">1</td>
    <td class="tg-4kyz">0.2</td>
    <td class="tg-4kyz">0.6</td>
    <td class="tg-4kyz">0.7</td>
    <td class="tg-4kyz">0.1</td>
    <td class="tg-4kyz">1</td>
  </tr>
  <tr>
    <td class="tg-4kyz">1</td>
    <td class="tg-4kyz">0</td>
    <td class="tg-4kyz">1</td>
    <td class="tg-4kyz">0.3</td>
    <td class="tg-4kyz">0.2</td>
    <td class="tg-4kyz">0.3</td>
    <td class="tg-4kyz">0.9</td>
    <td class="tg-4kyz">1</td>
  </tr>
  <tr>
    <td class="tg-4kyz">1</td>
    <td class="tg-4kyz">1</td>
    <td class="tg-4kyz">1</td>
    <td class="tg-4kyz">0.2</td>
    <td class="tg-4kyz">0.1</td>
    <td class="tg-4kyz">0.3</td>
    <td class="tg-4kyz">0.8</td>
    <td class="tg-4kyz">0</td>
  </tr>
</tbody></table>

In [4]:
import numpy as np

def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)

    return 1/(1+np.exp(-x))
    
X = np.array([[0,0,1],
            [0,1,1],
            [1,0,1],
            [1,1,1]])
                
y = np.array([[0],
            [1],
            [1],
            [0]])

np.random.seed(1)

# randomly initialize our weights with mean 0
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1

for j in xrange(60000):

    # Feed forward through layers 0, 1, and 2
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))
    l2 = nonlin(np.dot(l1,syn1))

    # how much did we miss the target value?
    l2_error = y - l2
    
    if (j% 10000) == 0:
        print "Error:" + str(np.mean(np.abs(l2_error)))
        
    # in what direction is the target value?
    # were we really sure? if so, don't change too much.
    l2_delta = l2_error*nonlin(l2,deriv=True)

    # how much did each l1 value contribute to the l2 error (according to the weights)?
    l1_error = l2_delta.dot(syn1.T)
    
    # in what direction is the target l1?
    # were we really sure? if so, don't change too much.
    l1_delta = l1_error * nonlin(l1,deriv=True)

    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta)
    
    if (j == 0) or (j == 20000):
        print " "
        print "iter:"+ str(j)
        print "Hidden Layer result in iter:"+ str(j)
        print l1
        print "Output layer result in iter:"+ str(j)
        print l2
        print "Weights in l1 in iter:"+ str(j)
        print syn0
        print "Weights in l2 in iter:"+ str(j)
        print syn1

print ""
print "Final output"
print l2


Error:0.496410031903
 
iter:0
Hidden Layer result in iter:0
[[ 0.44856632  0.51939863  0.45968497  0.59156505]
 [ 0.28639589  0.32350963  0.31236398  0.51538526]
 [ 0.40795614  0.62674606  0.23841622  0.49377636]
 [ 0.25371248  0.42628115  0.14321233  0.41732254]]
Output layer result in iter:0
[[ 0.47372957]
 [ 0.48895696]
 [ 0.54384086]
 [ 0.54470837]]
Weights in l1 in iter:0
[[-0.16699282  0.43568423 -1.00352547 -0.3968903 ]
 [-0.7067957  -0.8191728  -0.63773812 -0.3092039 ]
 [-0.20566016  0.07150791 -0.16356387  0.37002849]]
Weights in l2 in iter:0
[[-0.59560936]
 [ 0.74954163]
 [-0.95199413]
 [ 0.33638369]]
Error:0.00858452565325
Error:0.00578945986251
 
iter:20000
Hidden Layer result in iter:20000
[[  6.76071621e-01   1.28168162e-01   9.21470647e-01   9.95877626e-01]
 [  1.88772093e-01   5.21962936e-04   1.76602176e-02   8.90030167e-01]
 [  9.93442489e-01   8.83064272e-01   2.38921162e-02   8.11403421e-01]
 [  9.44105922e-01   2.61256437e-02   3.74994886e-05   1.25978836e-01]]
Out