<table class="tg">
  <tbody><tr>
    <th class="tg-5rcs" colspan="3">Inputs (l0)</th>
    <th class="tg-5rcs" colspan="4">Hidden Weights (l1)</th>
    <th class="tg-5rcs">Output (l2)</th>
  </tr>
  <tr>
    <td class="tg-4kyz">0</td>
    <td class="tg-4kyz">0</td>
    <td class="tg-4kyz">1</td>
    <td class="tg-4kyz">0.1</td>
    <td class="tg-4kyz">0.2</td>
    <td class="tg-4kyz">0.5</td>
    <td class="tg-4kyz">0.2</td>
    <td class="tg-4kyz">0</td>
  </tr>
  <tr>
    <td class="tg-4kyz">0</td>
    <td class="tg-4kyz">1</td>
    <td class="tg-4kyz">1</td>
    <td class="tg-4kyz">0.2</td>
    <td class="tg-4kyz">0.6</td>
    <td class="tg-4kyz">0.7</td>
    <td class="tg-4kyz">0.1</td>
    <td class="tg-4kyz">1</td>
  </tr>
  <tr>
    <td class="tg-4kyz">1</td>
    <td class="tg-4kyz">0</td>
    <td class="tg-4kyz">1</td>
    <td class="tg-4kyz">0.3</td>
    <td class="tg-4kyz">0.2</td>
    <td class="tg-4kyz">0.3</td>
    <td class="tg-4kyz">0.9</td>
    <td class="tg-4kyz">1</td>
  </tr>
  <tr>
    <td class="tg-4kyz">1</td>
    <td class="tg-4kyz">1</td>
    <td class="tg-4kyz">1</td>
    <td class="tg-4kyz">0.2</td>
    <td class="tg-4kyz">0.1</td>
    <td class="tg-4kyz">0.3</td>
    <td class="tg-4kyz">0.8</td>
    <td class="tg-4kyz">0</td>
  </tr>
</tbody></table>

In [6]:
import numpy as np

def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)

    return 1/(1+np.exp(-x))
    
X = np.array([[0,0,1],
            [0,1,1],
            [1,0,1],
            [1,1,1]])
# ((Dim X (4,3) * Dim weight (3,5)) * Dim weight (5,1))
print "X: "
print X
print "Dim X: " + str(X.shape)

y = np.array([[0],
            [1],
            [1],
            [0]])

np.random.seed(1)

# randomly initialize our weights with mean 0
syn0 = 2*np.random.random((3,5)) - 1
print "Dim syn0: "+ str(syn0.shape)

syn1 = 2*np.random.random((5,1)) - 1
print "Dim syn1: "+ str(syn1.shape)

for j in xrange(60000):

    # Feed forward through layers 0, 1, and 2
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))
    l2 = nonlin(np.dot(l1,syn1))

    # how much did we miss the target value?
    l2_error = y - l2
    
    if (j% 10000) == 0:
        print "Error:" + str(np.mean(np.abs(l2_error)))
        
    # in what direction is the target value?
    # were we really sure? if so, don't change too much.
    l2_delta = l2_error*nonlin(l2,deriv=True)

    # how much did each l1 value contribute to the l2 error (according to the weights)?
    l1_error = l2_delta.dot(syn1.T)
    
    # in what direction is the target l1?
    # were we really sure? if so, don't change too much.
    l1_delta = l1_error * nonlin(l1,deriv=True)

    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta)
    
    if (j == 0) or (j == 20000):
        print " "
        print "iter:"+ str(j)
        print "Hidden Layer result in iter:"+ str(j)
        print l1
        print "Output layer result in iter:"+ str(j)
        print l2
        print "Weights in l1 in iter:"+ str(j)
        print syn0
        print "Weights in l2 in iter:"+ str(j)
        print syn1

print ""
print "Final output"
print l2


X: 
[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]
Dim X: (4, 3)
Dim syn0: (3, 5)
Dim syn1: (5, 1)
Error:0.500628229093
 
iter:0
Hidden Layer result in iter:0
[[ 0.45968497  0.59156505  0.35638354  0.68053573  0.27984616]
 [ 0.27350061  0.43609134  0.28905583  0.63408219  0.29575574]
 [ 0.41883274  0.6923413   0.16926199  0.58925829  0.16087756]
 [ 0.24179019  0.54577358  0.1301373   0.53853219  0.1716356 ]]
Output layer result in iter:0
[[ 0.36407664]
 [ 0.35903039]
 [ 0.3839558 ]
 [ 0.38142246]]
Weights in l1 in iter:0
[[-0.15948822  0.43920538 -0.998562   -0.40461529 -0.71063999]
 [-0.81095517 -0.62978911 -0.30651624 -0.21499494  0.06680855]
 [-0.15228865  0.36636449 -0.58859765  0.73551981 -0.95766987]]
Weights in l2 in iter:0
[[ 0.38180053]
 [-0.0991604 ]
 [ 0.14292887]
 [-0.64566021]
 [-0.57576427]]
Error:0.00899024507125
Error:0.0060486255435
 
iter:20000
Hidden Layer result in iter:20000
[[  1.66641696e-01   7.10421919e-01   1.91107488e-01   9.29271791e-01
    8.79096324e-01]
 [  3.27288