In [1]:
import numpy as np

J = np.array([
    [1, 2, 1],
])
print "Input: "
print J

W1 = np.array([
    [1, 1, 1, 1, 1],
    [2, 2, 2, 2, 2],
    [1, 1, 1, 1, 1]
])
print ""
print "W1: "
print W1

y = J.dot(W1)
print ""
print "Output-HiddenLayer: "
print y

W2 = np.array([
    [1,1,1,1,1]
]).T
print ""
print "W2: "
print W2

y2 = y.dot(W2)
print ""
print "Output-Final:"
print y2

Input: 
[[1 2 1]]

W1: 
[[1 1 1 1 1]
 [2 2 2 2 2]
 [1 1 1 1 1]]

Output-HiddenLayer: 
[[6 6 6 6 6]]

W2: 
[[1]
 [1]
 [1]
 [1]
 [1]]

Output-Final:
[[30]]


In [20]:
W1[0,:]

array([1, 1, 1, 1, 1])