In [2]:
import numpy as np

# sigmoid function
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))
    
# input dataset
X = np.array([  [0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1], ])
    
# output dataset            
y = np.array([[0,0,1,1]]).T

#finalWeight got from training backpropagation
syn0 = np.array ([ 
    [ 9.67299303],
    [-0.2078435 ],
    [-4.62963669] ])

print ""
print "Final weights:"
print syn0
l1 = np.dot(X, syn0)
print 'l1:'
print l1
finalOutput = nonlin(l1)
print " "
print "Final Output:"
print finalOutput


Final weights:
[[ 9.67299303]
 [-0.2078435 ]
 [-4.62963669]]
l1:
[[-4.62963669]
 [-4.83748019]
 [ 5.04335634]
 [ 4.83551284]]
 
Final Output:
[[ 0.009664  ]
 [ 0.00786466]
 [ 0.99358931]
 [ 0.99211997]]


In [21]:
l1_error = y - l1

l = 1/(1+np.exp(-0.30226848))
print l1_error

[[ 4.62963669]
 [ 4.83748019]
 [-4.04335634]
 [-3.83551284]]


In [22]:
a = np.array([[1,2,3,4]]).T
b = np.array([[1,2,3,4]]).T
print a * b


[[ 1]
 [ 4]
 [ 9]
 [16]]


In [23]:
print X.T

[[0 0 1 1]
 [0 1 0 1]
 [1 1 1 1]]


In [29]:
yz = np.array([[0,0,1,1,5,6]]).T
X[*yz

ValueError: operands could not be broadcast together with shapes (4,3) (6,1) 

In [20]:
slope = nonlin(l1, True)
l1_delta = l1_error * slope
print l1_delta

NameError: name 'l1_error' is not defined

In [25]:
syn0 += np.dot(X.T, l1_delta)
print syn0

[[ 163.26146362]
 [ -65.67597308]
 [-108.30831268]]
